x-common-env: &service_env
  SP1_PROVER: ${SP1_PROVER:-mock}
  NETWORK_PRIVATE_KEY: ${NETWORK_PRIVATE_KEY}

services:
  zkvm-service:
    # build: .
    image: ups03/zkvm-service:latest
    container_name: zkvm-service
    ports:
      - "38080:38080"
    environment: *service_env
    restart: always
